'use server';

/**
 * @fileOverview A generative AI brief assistant flow.
 *
 * - generateAICampaignBrief - A function that handles the campaign brief generation process.
 * - GenerateAICampaignBriefInput - The input type for the generateAICampaignBrief function.
 * - GenerateAICampaignBriefOutput - The return type for the generateAICampaignBrief function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateAICampaignBriefInputSchema = z.object({
  brandName: z.string().describe('The name of the brand.'),
  productDescription: z.string().describe('A description of the product or service.'),
  targetAudience: z.string().describe('The target audience for the campaign.'),
  campaignGoal: z.string().describe('The primary goal of the campaign (e.g., increase brand awareness, drive sales).'),
  budget: z.string().describe('The budget for the campaign.'),
});
export type GenerateAICampaignBriefInput = z.infer<typeof GenerateAICampaignBriefInputSchema>;

const GenerateAICampaignBriefOutputSchema = z.object({
  campaignBrief: z.string().describe('A detailed campaign brief generated by the AI.'),
});
export type GenerateAICampaignBriefOutput = z.infer<typeof GenerateAICampaignBriefOutputSchema>;

export async function generateAICampaignBrief(input: GenerateAICampaignBriefInput): Promise<GenerateAICampaignBriefOutput> {
  return generateAICampaignBriefFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateAICampaignBriefPrompt',
  input: {schema: GenerateAICampaignBriefInputSchema},
  output: {schema: GenerateAICampaignBriefOutputSchema},
  prompt: `You are an AI assistant that specializes in creating campaign briefs for brands.

  Based on the information provided, generate a comprehensive campaign brief that includes:

  *   Campaign objectives
  *   Target audience insights
  *   Key messaging
  *   Suggested deliverables
  *   Timeline
  *   Budget allocation

  Brand Name: {{{brandName}}}
  Product Description: {{{productDescription}}}
  Target Audience: {{{targetAudience}}}
  Campaign Goal: {{{campaignGoal}}}
  Budget: {{{budget}}}

  Campaign Brief:`,
});

const generateAICampaignBriefFlow = ai.defineFlow(
  {
    name: 'generateAICampaignBriefFlow',
    inputSchema: GenerateAICampaignBriefInputSchema,
    outputSchema: GenerateAICampaignBriefOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
